version: "3"
services:
    quidordine-php:
        image: "pauulog/php-docker-dev:latest"
        container_name: "quidordine-php"
        links:
          - "quidordine-mariadb:mariadb.host"
        volumes:
            - "./:/quidordine:rw"
        working_dir: /quidordine
        restart: always
    quidordine-nginx:
        image: "nginx:1-alpine"
        container_name: "quidordine-nginx"
        links:
          - "quidordine-php:quidordine-php.host"
        ports:
          - 8080:80
        volumes:
            - "./:/quidordine:rw"
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:r"
        working_dir: /quidordine
        restart: always
    quidordine-mariadb:
        image: "mariadb:10.6"
        container_name: "quidordine-mariadb"
        volumes:
            - "._mysql_data_dir/:/var/lib/mysql:rw"
        ports:
          - 3307:3306
        environment:
          - MARIADB_USER
          - MARIADB_PASSWORD
          - MARIADB_DATABASE
          - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
        restart: always